### PR TITLE
Credentials

### PR DESCRIPTION
**Pull request by k1kolev**
An article presenting the ways to try ERP.net for free. 
Meant as a central information source for trying ERP.net, providing the URLs and sign in details.

Editing TOC to include the article on trying ERP.net for free

### CODE REVIEW

**Review by thristozova — CHANGES_REQUESTED** [review]
I have a few comments:

1. "After installing and startup, the desktop client will ask you to sign in with the database URL and your credentials."

 I feel that it's better to state the database URL explicitly because the audience of the article will probably be inexperienced and it might lead to confusion.

An example:
"After installing and startup, the desktop client will ask you to sign in with the database URL, in this case, https://demodb.my.erp.net , and your credentials."

2. The user "User: Admin" starts with a capital letter.

It is better to be written exactly the way it is defined in the database, namely "admin" in lowercase.

Currently, the logins are not case-sensitive, but if that changes - these credentials will automatically stop working.

3. "Most ERP instances should, by default, be configured to NOT accept basic authentication. 
However, for demonstration purposes, DemoDB is configured to allow it. "

This is not true. Even though the users are using a user and password - this is not basic auth. These credentials are still authorized by the id site. 
You can just remove it.

**Comment by k1kolev** [comment]
All remarks have been addressed and the article was corrected.

**Review by thristozova — CHANGES_REQUESTED** [review]
I am sorry, I saw that I missed something.

There is a "## Can I Try Your Newly Released Solutions?'" section that sends the users to testdb.

However, the version there usually contains unfinished or partial developments and it is expected that the users might encounter some inconsistencies of the work of the app and even some errors.

Let's put a warning in a visible place in this section so that users know about this possibility and won't be disappointed on their first encounter with the program.

**Comment by k1kolev** [comment]
Added a small correction suggested by Tisha about the last note, making it more accurate.

**Review by thristozova — APPROVED** [review]

**Pull request merged**
