### PR TITLE
Pab branch

### PR DESCRIPTION
**Pull request by k1kolev**
Proposal for an article presenting the concept of Projected available balance. 

Added links to docs.erp.net/tech for demonstrating an example, disclosing the algorithm, as well as other deeper insight gaining for readers.

Adding Projected available balance article to the toc file.

### CODE REVIEW

**Comment by k1kolev** [comment]
Added a simple example to illustrate the concept.

Changed the headings a little bit, not to sound too tech savvy.

Emphasized on the real-time operation of PAB in ERP.net, and how this can help users stay tuned to their inventory movements.

**Comment by k1kolev** [comment]
@thristozova, article ready for your review.

**Comment by thristozova** [comment]
An excellent article! 

My only issue is with the PAB example.
I find the choice of numbers on day one a bit misleading. It makes me think that 15 is the result of 20-5, but it is actually the result of 30-20+5.

| Day | Orders | Supplies | PAB | 
| - | - | - | - | 
| Starting | N/A | N/A | 30 | 
| 1 | 20 | 5 | 15 |

**Review by thristozova — CHANGES_REQUESTED** [review]
An excellent article! 

My only issue is with the PAB example.
I find the choice of numbers on day one a bit misleading. It makes me think that 15 is the result of 20-5, but it is actually the result of 30-20+5.

| Day | Orders | Supplies | PAB | 
| - | - | - | - | 
| Starting | N/A | N/A | 30 | 
| 1 | 20 | 5 | 15 |

**Comment by k1kolev** [comment]
> An excellent article!
> 
> My only issue is with the PAB example. I find the choice of numbers on day one a bit misleading. It makes me think that 15 is the result of 20-5, but it is actually the result of 30-20+5.
> 
> Day	Orders	Supplies	PAB
> Starting	N/A	N/A	30
> 1	20	5	15

I accept the pertinent remark. Number of orders and supplies changed to avoid ambiguity in perception of the PAB concept.

**Comment by k1kolev** [comment]
@i-argentinski, article ready for your decision.

**Review by thristozova — APPROVED** [review]

**Pull request merged**
